config/routes.rb
Mowheels::Application.routes.draw do
  resources :recipient_menus

  resources :menus

  resources :recipients

  resources :delivery

  devise_for :users
   root "pages#home"
   get "about" => "pages#about"

  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :recipient_menus
  has_many :recipients, through: :recipient_menus
  validates :menu_date, uniqueness: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:menu_date, :main_dish1, :main_dish2, :side1, :side2, :side3, :diet)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_date %><br>
    <%= f.date_select :menu_date %>
  </div>
  <div class="field">
    <%= f.label :main_dish1 %><br>
    <%= f.text_field :main_dish1 %>
  </div>
  <div class="field">
    <%= f.label :main_dish2 %><br>
    <%= f.text_field :main_dish2 %>
  </div>
  <div class="field">
    <%= f.label :side1 %><br>
    <%= f.text_field :side1 %>
  </div>
  <div class="field">
    <%= f.label :side2 %><br>
    <%= f.text_field :side2 %>
  </div>
  <div class="field">
    <%= f.label :side3 %><br>
    <%= f.text_field :side3 %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Menu date</th>
      <th>Main dish1</th>
      <th>Main dish2</th>
      <th>Side1</th>
      <th>Side2</th>
      <th>Side3</th>
      <th>Diet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.menu_date %></td>
        <td><%= menu.main_dish1 %></td>
        <td><%= menu.main_dish2 %></td>
        <td><%= menu.side1 %></td>
        <td><%= menu.side2 %></td>
        <td><%= menu.side3 %></td>
        <td><%= menu.diet %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu date:</strong>
  <%= @menu.menu_date %>
</p>

<p>
  <strong>Main dish1:</strong>
  <%= @menu.main_dish1 %>
</p>

<p>
  <strong>Main dish2:</strong>
  <%= @menu.main_dish2 %>
</p>

<p>
  <strong>Side1:</strong>
  <%= @menu.side1 %>
</p>

<p>
  <strong>Side2:</strong>
  <%= @menu.side2 %>
</p>

<p>
  <strong>Side3:</strong>
  <%= @menu.side3 %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @menu.diet %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>