config/routes.rb
Mowheels::Application.routes.draw do
  resources :recipient_menus

  resources :menus

  resources :recipients

  resources :delivery

  devise_for :users
   root "pages#home"
   get "about" => "pages#about"

  

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base

  has_many :recipient_menus, dependent: :destroy
  has_many :menus, through: :recipient_menus

  def first_last_name
    [first_name, last_name].reject{|v| v.blank?}.join(" ")
  end

end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipient }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:first_name, :last_name, :address, :city, :state, :postal_code, :route_number, :print_sort, :coldpref1, :coldpref2, :hotpref, :recipients_phone, :birthdate, :doctor_name, :doctor_phone, :diet, :substitutions, :contact_name, :contact_relationship, :contact_work_phone, :contact_phone, :note, :start_date, :end_date, :status, :referred_by, :directions_to_home, :assisted, :payment_details, :assistance_amount, :billing_name, :billing_address, :billing_city, :billing_state, :billing_zip, :termination_reason, :mon_hot, :tue_hot, :wed_hot, :thur_hot, :fri_hot, :sat_hot, :sun_hot)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= form_for(@recipient) do |f| %>
  <% if @recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% @recipient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :route_number %><br>
    <%= f.number_field :route_number %>
  </div>
  <div class="field">
    <%= f.label :print_sort %><br>
    <%= f.number_field :print_sort %>
  </div>
  <div class="field">
    <%= f.label :coldpref1 %><br>
    <%= f.text_field :coldpref1 %>
  </div>
  <div class="field">
    <%= f.label :coldpref2 %><br>
    <%= f.text_field :coldpref2 %>
  </div>
  <div class="field">
    <%= f.label :hotpref %><br>
    <%= f.text_field :hotpref %>
  </div>
  <div class="field">
    <%= f.label :recipients_phone %><br>
    <%= f.text_field :recipients_phone %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :doctor_name %><br>
    <%= f.text_field :doctor_name %>
  </div>
  <div class="field">
    <%= f.label :doctor_phone %><br>
    <%= f.text_field :doctor_phone %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>
  <div class="field">
    <%= f.label :substitutions %><br>
    <%= f.text_field :substitutions %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_relationship %><br>
    <%= f.text_field :contact_relationship %>
  </div>
  <div class="field">
    <%= f.label :contact_work_phone %><br>
    <%= f.text_field :contact_work_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :referred_by %><br>
    <%= f.text_field :referred_by %>
  </div>
  <div class="field">
    <%= f.label :directions_to_home %><br>
    <%= f.text_area :directions_to_home %>
  </div>
  <div class="field">
    <%= f.label :assisted %><br>
    <%= f.text_field :assisted %>
  </div>
  <div class="field">
    <%= f.label :payment_details %><br>
    <%= f.text_area :payment_details %>
  </div>
  <div class="field">
    <%= f.label :assistance_amount %><br>
    <%= f.text_field :assistance_amount %>
  </div>
  <div class="field">
    <%= f.label :billing_name %><br>
    <%= f.text_field :billing_name %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_field :billing_address %>
  </div>
  <div class="field">
    <%= f.label :billing_city %><br>
    <%= f.text_field :billing_city %>
  </div>
  <div class="field">
    <%= f.label :billing_state %><br>
    <%= f.text_field :billing_state %>
  </div>
  <div class="field">
    <%= f.label :billing_zip %><br>
    <%= f.text_field :billing_zip %>
  </div>
  <div class="field">
    <%= f.label :termination_reason %><br>
    <%= f.text_area :termination_reason %>
  </div>
  <div class="field">
    <%= f.label :mon_hot %><br>
    <%= f.text_field :mon_hot %>
  </div>
  <div class="field">
    <%= f.label :tue_hot %><br>
    <%= f.text_field :tue_hot %>
  </div>
  <div class="field">
    <%= f.label :wed_hot %><br>
    <%= f.text_field :wed_hot %>
  </div>
  <div class="field">
    <%= f.label :thur_hot %><br>
    <%= f.text_field :thur_hot %>
  </div>
  <div class="field">
    <%= f.label :fri_hot %><br>
    <%= f.text_field :fri_hot %>
  </div>
  <div class="field">
    <%= f.label :sat_hot %><br>
    <%= f.text_field :sat_hot %>
  </div>
  <div class="field">
    <%= f.label :sun_hot %><br>
    <%= f.text_field :sun_hot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Route number</th>
      <th>Print sort</th>
      <th>Coldpref1</th>
      <th>Coldpref2</th>
      <th>Hotpref</th>
      <th>Recipients phone</th>
      <th>Birthdate</th>
      <th>Doctor name</th>
      <th>Doctor phone</th>
      <th>Diet</th>
      <th>Substitutions</th>
      <th>Contact name</th>
      <th>Contact relationship</th>
      <th>Contact work phone</th>
      <th>Contact phone</th>
      <th>Note</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th>Referred by</th>
      <th>Directions to home</th>
      <th>Assisted</th>
      <th>Payment details</th>
      <th>Assistance amount</th>
      <th>Billing name</th>
      <th>Billing address</th>
      <th>Billing city</th>
      <th>Billing state</th>
      <th>Billing zip</th>
      <th>Termination reason</th>
      <th>Mon hot</th>
      <th>Tue hot</th>
      <th>Wed hot</th>
      <th>Thur hot</th>
      <th>Fri hot</th>
      <th>Sat hot</th>
      <th>Sun hot</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.first_name %></td>
        <td><%= recipient.last_name %></td>
        <td><%= recipient.address %></td>
        <td><%= recipient.city %></td>
        <td><%= recipient.state %></td>
        <td><%= recipient.postal_code %></td>
        <td><%= recipient.route_number %></td>
        <td><%= recipient.print_sort %></td>
        <td><%= recipient.coldpref1 %></td>
        <td><%= recipient.coldpref2 %></td>
        <td><%= recipient.hotpref %></td>
        <td><%= recipient.recipients_phone %></td>
        <td><%= recipient.birthdate %></td>
        <td><%= recipient.doctor_name %></td>
        <td><%= recipient.doctor_phone %></td>
        <td><%= recipient.diet %></td>
        <td><%= recipient.substitutions %></td>
        <td><%= recipient.contact_name %></td>
        <td><%= recipient.contact_relationship %></td>
        <td><%= recipient.contact_work_phone %></td>
        <td><%= recipient.contact_phone %></td>
        <td><%= recipient.note %></td>
        <td><%= recipient.start_date %></td>
        <td><%= recipient.end_date %></td>
        <td><%= recipient.status %></td>
        <td><%= recipient.referred_by %></td>
        <td><%= recipient.directions_to_home %></td>
        <td><%= recipient.assisted %></td>
        <td><%= recipient.payment_details %></td>
        <td><%= recipient.assistance_amount %></td>
        <td><%= recipient.billing_name %></td>
        <td><%= recipient.billing_address %></td>
        <td><%= recipient.billing_city %></td>
        <td><%= recipient.billing_state %></td>
        <td><%= recipient.billing_zip %></td>
        <td><%= recipient.termination_reason %></td>
        <td><%= recipient.mon_hot %></td>
        <td><%= recipient.tue_hot %></td>
        <td><%= recipient.wed_hot %></td>
        <td><%= recipient.thur_hot %></td>
        <td><%= recipient.fri_hot %></td>
        <td><%= recipient.sat_hot %></td>
        <td><%= recipient.sun_hot %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @recipient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @recipient.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recipient.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @recipient.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @recipient.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @recipient.postal_code %>
</p>

<p>
  <strong>Route number:</strong>
  <%= @recipient.route_number %>
</p>

<p>
  <strong>Print sort:</strong>
  <%= @recipient.print_sort %>
</p>

<p>
  <strong>Coldpref1:</strong>
  <%= @recipient.coldpref1 %>
</p>

<p>
  <strong>Coldpref2:</strong>
  <%= @recipient.coldpref2 %>
</p>

<p>
  <strong>Hotpref:</strong>
  <%= @recipient.hotpref %>
</p>

<p>
  <strong>Recipients phone:</strong>
  <%= @recipient.recipients_phone %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @recipient.birthdate %>
</p>

<p>
  <strong>Doctor name:</strong>
  <%= @recipient.doctor_name %>
</p>

<p>
  <strong>Doctor phone:</strong>
  <%= @recipient.doctor_phone %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @recipient.diet %>
</p>

<p>
  <strong>Substitutions:</strong>
  <%= @recipient.substitutions %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @recipient.contact_name %>
</p>

<p>
  <strong>Contact relationship:</strong>
  <%= @recipient.contact_relationship %>
</p>

<p>
  <strong>Contact work phone:</strong>
  <%= @recipient.contact_work_phone %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @recipient.contact_phone %>
</p>

<p>
  <strong>Note:</strong>
  <%= @recipient.note %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @recipient.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @recipient.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @recipient.status %>
</p>

<p>
  <strong>Referred by:</strong>
  <%= @recipient.referred_by %>
</p>

<p>
  <strong>Directions to home:</strong>
  <%= @recipient.directions_to_home %>
</p>

<p>
  <strong>Assisted:</strong>
  <%= @recipient.assisted %>
</p>

<p>
  <strong>Payment details:</strong>
  <%= @recipient.payment_details %>
</p>

<p>
  <strong>Assistance amount:</strong>
  <%= @recipient.assistance_amount %>
</p>

<p>
  <strong>Billing name:</strong>
  <%= @recipient.billing_name %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @recipient.billing_address %>
</p>

<p>
  <strong>Billing city:</strong>
  <%= @recipient.billing_city %>
</p>

<p>
  <strong>Billing state:</strong>
  <%= @recipient.billing_state %>
</p>

<p>
  <strong>Billing zip:</strong>
  <%= @recipient.billing_zip %>
</p>

<p>
  <strong>Termination reason:</strong>
  <%= @recipient.termination_reason %>
</p>

<p>
  <strong>Mon hot:</strong>
  <%= @recipient.mon_hot %>
</p>

<p>
  <strong>Tue hot:</strong>
  <%= @recipient.tue_hot %>
</p>

<p>
  <strong>Wed hot:</strong>
  <%= @recipient.wed_hot %>
</p>

<p>
  <strong>Thur hot:</strong>
  <%= @recipient.thur_hot %>
</p>

<p>
  <strong>Fri hot:</strong>
  <%= @recipient.fri_hot %>
</p>

<p>
  <strong>Sat hot:</strong>
  <%= @recipient.sat_hot %>
</p>

<p>
  <strong>Sun hot:</strong>
  <%= @recipient.sun_hot %>
</p>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>