config/routes.rb
Mowheels::Application.routes.draw do
  resources :recipient_menus

  resources :menus

  resources :recipients

  resources :delivery

  devise_for :users
   root "pages#home"
   get "about" => "pages#about"

  

end

app/models/recipient_menu.rb
class RecipientMenu < ActiveRecord::Base
	belongs_to :recipient
	belongs_to :menu
end

app/controllers/recipient_menus_controller.rb
class RecipientMenusController < ApplicationController
  before_action :set_recipient_menu, only: [:show, :edit, :update, :destroy]

  # GET /recipient_menus
  # GET /recipient_menus.json
  def index
    @recipient_menus = RecipientMenu.all
  end

  # GET /recipient_menus/1
  # GET /recipient_menus/1.json
  def show
  end

  # GET /recipient_menus/new
  def new
    @recipient_menu = RecipientMenu.new

    if params[:recipient_menu] && params[:recipient_menu][:menu_id]
      @menu = Menu.find params[:recipient_menu][:menu_id]
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /recipient_menus/1/edit
  def edit
  end

  # POST /recipient_menus
  # POST /recipient_menus.json
  def create
    @recipient_menu = RecipientMenu.new(recipient_menu_params)

    respond_to do |format|
      if @recipient_menu.save
        format.html { redirect_to @recipient_menu, notice: 'Recipient menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipient_menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipient_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipient_menus/1
  # PATCH/PUT /recipient_menus/1.json
  def update
    respond_to do |format|
      if @recipient_menu.update(recipient_menu_params)
        format.html { redirect_to @recipient_menu, notice: 'Recipient menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipient_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipient_menus/1
  # DELETE /recipient_menus/1.json
  def destroy
    @recipient_menu.destroy
    respond_to do |format|
      format.html { redirect_to recipient_menus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient_menu
      @recipient_menu = RecipientMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_menu_params
      params.require(:recipient_menu).permit(:recipient_id, :menu_id, :menu_date, :main_dish1, :main_dish2, :main_dish_choice, :side1, :side2, :side3, :side_choice, :diet)
    end
end

app/helpers/recipient_menus_helper.rb
module RecipientMenusHelper
end

app/views/recipient_menus/_form.html.erb
x<%= form_for(@recipient_menu) do |f| %>
  <% if @recipient_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient_menu.errors.count, "error") %> prohibited this recipient_menu from being saved:</h2>

      <ul>
      <% @recipient_menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :recipient_id %><br>
   <%# f.number_field :recipient_id %>
   <%= f.collection_select(:recipient_id, Recipient.all, :id, :first_last_name, {:selected => @recipient.try(:id)}) %>
  </div>

<%# I am trying to find the menu_id selected by the user below and then %>
<%# get the menu object to be used main_dish1 , main_dish2, etc%>

  <div class="field">
    <%= f.label :menu_id %><br>
    <%= f.collection_select :menu_id, Menu.all, :id, :menu_date,
      { selected: @menu.try(:id), include_blank: true },
      { data: { remote: true } } %>
  </div>

  <div class="field">
    <%= f.label :main_dish_choice %><br>
    <%= f.select :main_dish_choice, [] %>
  </div>

  <div class="field">
    <%= f.label :side_choice %><br>
    <%= f.select :side_choice, [] %>
  </div>

  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/recipient_menus/edit.html.erb
<h1>Editing recipient_menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient_menu %> |
<%= link_to 'Back', recipient_menus_path %>

app/views/recipient_menus/index.html.erb
<h1>Listing recipient_menus</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Menu</th>
      <th>Menu date</th>
      <th>Main dish1</th>
      <th>Main dish2</th>
      <th>Main dish choice</th>
      <th>Side1</th>
      <th>Side2</th>
      <th>Side3</th>
      <th>Side choice</th>
      <th>Diet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipient_menus.each do |recipient_menu| %>
      <tr>
        <td><%= recipient_menu.recipient_id %></td>
        <td><%= recipient_menu.menu_id %></td>
        <td><%= recipient_menu.menu_date %></td>
        <td><%= recipient_menu.main_dish1 %></td>
        <td><%= recipient_menu.main_dish2 %></td>
        <td><%= recipient_menu.main_dish_choice %></td>
        <td><%= recipient_menu.side1 %></td>
        <td><%= recipient_menu.side2 %></td>
        <td><%= recipient_menu.side3 %></td>
        <td><%= recipient_menu.side_choice %></td>
        <td><%= recipient_menu.diet %></td>
        <td><%= link_to 'Show', recipient_menu %></td>
        <td><%= link_to 'Edit', edit_recipient_menu_path(recipient_menu) %></td>
        <td><%= link_to 'Destroy', recipient_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient menu', new_recipient_menu_path %>

app/views/recipient_menus/new.html.erb
<% javascript 'dynamic_menus' %>

<h1>New recipient_menu</h1>

<%= render 'form' %>

<%= link_to 'Back', recipient_menus_path %>

app/views/recipient_menus/new.js.erb
<%
  main_choices = [@menu.main_dish1, @menu.main_dish2].compact.map{|m| content_tag :option, m }.join('').html_safe
  side_choices = [@menu.side1, @menu.side2, @menu.side3].compact.map{|s| content_tag :option, s }.join('').html_safe
%>
$('#recipient_menu_main_dish_choice').html(
  '<%= escape_javascript main_choices %>'
)

$('#recipient_menu_side_choice').html(
  '<%= escape_javascript side_choices %>'
)

$('#recipient_menu_diet').val('<%= escape_javascript @menu.diet %>')

app/views/recipient_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @recipient_menu.recipient_id %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @recipient_menu.menu_id %>
</p>

<p>
  <strong>Menu date:</strong>
  <%= @recipient_menu.menu_date %>
</p>

<p>
  <strong>Main dish1:</strong>
  <%= @recipient_menu.main_dish1 %>
</p>

<p>
  <strong>Main dish2:</strong>
  <%= @recipient_menu.main_dish2 %>
</p>

<p>
  <strong>Main dish choice:</strong>
  <%= @recipient_menu.main_dish_choice %>
</p>

<p>
  <strong>Side1:</strong>
  <%= @recipient_menu.side1 %>
</p>

<p>
  <strong>Side2:</strong>
  <%= @recipient_menu.side2 %>
</p>

<p>
  <strong>Side3:</strong>
  <%= @recipient_menu.side3 %>
</p>

<p>
  <strong>Side choice:</strong>
  <%= @recipient_menu.side_choice %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @recipient_menu.diet %>
</p>

<%= link_to 'Edit', edit_recipient_menu_path(@recipient_menu) %> |
<%= link_to 'Back', recipient_menus_path %>